### your site title here

title: ᲐᲕᲗᲐᲜᲓᲘᲚ ᲤᲐᲜᲒᲐᲜᲘ
description: კომპიუტერული  მეცნიერებების მასწავლებელი, ტრენერი

baseurl: ""#name of GitHub repository
url: "" #custom url to be used instead of GitHub repository
email: #

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
# twitter: "#"
# linkedin: "#"
# stackoverflow: "#"
github: "avtotrainer"
# researchgate: "#"
# orcid: "#"
# quora: "#"
# instagram: "#"
facebook: "/aphangani"


navigation:
  - title: ᲛᲗᲐᲕᲐᲠᲘ
    url: /
  - title: ᲡᲢᲐᲢᲘᲔᲑᲘ
    url: /articles
  - title: ᲑᲚᲝᲒᲘ
    url: /blog
  - title: ᲞᲘᲗᲝᲜᲘ
    url: /python
  - title: ლინუქსი
    url: /linux
  - title: ᲒᲐᲠᲔᲛᲝᲜᲘ
    url: /envi
  - title: ᲐᲠᲥᲘᲕᲘ
    url: /archive
  

# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - ikaro.md
      - tetri.md
      - club_ikaro.md
      - club_ruispiri.md
      - club_matani.md
      - club_sakobiano.md

  articles:
    output: true
    permalink: /articles/:name/
  python:
    output: true
    permalink: /python/:name/
    order:
      - venv.md
      - pip.md
  envi:
    output: true
    permalink: /envi/:name/
    order:
      - this_site.md
      - szh.md  
  linux:
    output: true
    permalink: /linux/:name/
    order:
      - this_site.md
      - szh.md  
sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
